{{- $chart_name := include "cronjobs.fullname" . }}
{{- $chart_labels := include "cronjobs.labels" . }}

{{- if .Values.configMaps }}
{{- range $name, $map := .Values.configMaps }}
---
apiVersion: "v1"
kind: "ConfigMap"
metadata:
  name: cleaner-config
  labels:
    {{- $chart_labels | nindent 4 }}
data:
  {{- range $name, $value := $map.data }}
  {{ $name }}: |
    {{- $value | nindent 4 }}
  {{- end }}
  {{- range $name, $path := $map.files }}
  {{ $name }}: |
    {{- $.Files.Get $path | nindent 4}}
  {{- end }}
{{- end }}
{{- end }}
