{{- $chart_name := include "cronjobs.fullname" . }}
{{- $chart_labels := include "cronjobs.labels" . }}

{{- if .Values.dockerConfigJson }}
---
apiVersion: v1
kind: Secret
metadata:
  name: registry
  labels:
    {{- $chart_labels | nindent 4 }}
  annotations:
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ .Values.dockerConfigJson | quote }}
{{- end }}

{{- range $name, $secret := .Values.secrets }}
{{- $checksum := toYaml $secret | sha256sum | trunc 20 | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $name }}
  labels:
    {{- $chart_labels | nindent 4 }}
type: Opaque
data:
  {{- range $name, $value := $secret.data }}
  {{ $name }}: {{ $value | b64enc | quote }}
  {{- end }}
  {{- range $name, $path := $secret.files }}
  {{ $name }}: {{ $.Files.Get $path | b64enc | quote }}
  {{- end }}
{{- end }}
