---
nameOverride: ""
fullnameOverride: ""

image:
  registry: harbor.cgi-dev.de
  repository: geoserver/housekeeper
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: dev
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
imagePullSecrets:
  - name: harbor-secret

# will create a kubernetes.io/dockerconfigjson secret
# and add it to imagePullSecrets
# i.e.
# AUTH=$( echo -n "$REGISTRY_USER:$REGISTRY_PASS" | base64 )
# DOCKER_CONFIG_JSON=$(echo -n '{ "auths": { "${REGISTRY_URL}": { "auth": "${AUTH}" } } }' | base64 | tr -d \"\n\")
# dockerConfigJson: $DOCKER_CONFIG_JSON

# secrets: {}
secrets:
  cleaner-email-pass:
    data:
      password: "somePassword"
  cleaner-db-pass:
    data:
      password: "AnotherPassword"
#  # strings and file contents are automatically base64 encoded
#  ssh-creds:
#    data:
#      ssh.key: "ssh-rsa AAAAB3N.....uFo42 your@key.comment"
#    files:
#      id-rsa.pub: ci/files/id-rsa.pub

# a global custom configMap that is mounted in every job
customConfigMap:

# global configMaps from string or files
# configMaps: {}
configMaps:
  cleaner-config:
    data:
      FIELDS: location,time
      COLUMN_TIME: time
      GLOBAL_RETENTION: ALL,120
      LAYERS: '"copernicus:sentinel3b;mosaic_indexes.copernicus_sentinel3a_olci_l2_chl_fullres;360","copernicus:sentinel3b;mosaic_indexes.copernicus_sentinel3b_olci_l1_rgb_fullres;120","copernicus_daily:sentinel3ab;mosaic_indexes.copernicus_daily_sentinel3ab_olci_l1_rgb_fulres;120","copernicus:sentinel3a;mosaic_indexes.copernicus_sentinel3a_olci_l1_rgb_fullres;120"'

# environment variables for all jobs
env: []

jobs: {}


serviceAccount:
  # Specifies whether a service account should be created
  create: false
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

# resources: {}
resources:
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances drpsychick run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
